### ISSUE TITLE
описание САМОЙ первой версии бота

### ISSUE THREAD

**Issue by kozhevnykov** [GooDRomka/QueueBot#1]
User story - функционал расписанный по каждому юзеру: 

Клиент:
1. Может посмотреть список магазинов
2. Может записаться в очередь в конкретный магазин
3. Может покинуть очередь в конкретном магазине (в т.ч. когда он закончил покупки)
4. Может посмотреть номер в очереди в каждом из магазинов

Магазин (магазин и очередь в магазине это одна сущность):
1. Создать магазин в боте
2. Списать одного(первого) в очереди в своем магазине (если я его отработал или он не появился)
3. Очистить очередь
4. Закрыть очередь и удалить из списка очередей (магазинов)
5. Показать имена следующих трех чуваков

**Comment by GooDRomka** [comment]
Необходимо добавить Токкены для создания магазина, которые мы лично будет давать, чтобы все пользователи не создавали себе по магазину и не засоряли список.
Тогда кнопка удалить магазин не нужна, он удаляется через админа, чтобы случайно магазин пользователь не мог удалить. 
Очередь тоже не вижу смысла очищять

**Comment by GooDRomka** [comment]
Нужно поработать с дизайном:
1. Нормальное отображение кнопок на телефоне
2. Нормальные названия для кнопок и действий

**Comment by GooDRomka** [comment]
Добавить рассылку для магазина
Добавить Тип Админ рассылка и управление
Добавить быструю запись
Авторизация магазина

**Comment by GooDRomka** [comment]
Посмотреть сколько человек в очереди и среднее время одного человека

**Comment by GooDRomka** [comment]
Функция вывода userList, shopList, shopNames для сохранения в файл

**Comment by GooDRomka** [comment]
1)Help и приветствие , там нужно написать, что все команды выполняются кнопками, без ввода
2) уведомления : о записи, о подходе очереди, просто отправить сообщение всем, кто в очереди, рассылка админа всем всем
3) ДИЗАЙН НОРМАЛЬНЫЙ
4) Посмотреть сколько человек в очереди и среднее время одного человека
5)
